[package]
name = "groth16"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-serialize = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.4"

[dev-dependencies]
ark-groth16 = "0.4"
